### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by zhihengGet** [unpreset/unocss-preset-palette#2]
最新的unocss@0.56.1 ...  

我看了unocs-preset-palette 使用 unocss/preset-mini, @unocss/preset-mini明明有export Theme不知道为什么

0.56.1/node_modules/unocss-preset-palette/dist/index.mjs:3
export { Theme } from '@unocss/preset-mini';
         ^^^^^
SyntaxError: The requested module '@unocss/preset-mini' does not provide an export named 'Theme'    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)

**Comment by chizukicn** [comment]
感谢！因为Theme只是个type😢
