### ISSUE TITLE
cssVarName无法改掉format后缀

### ISSUE THREAD

**Issue by zhihengGet** [unpreset/unocss-preset-palette#3]
生成的css var 里 有 -hsl or -rgb,  能不能去掉, 现在无法通过caaVarName生成自己想要的... 多谢

比如 hsla(var(--un-palette-primary-color-hsl)

**Comment by zhihengGet** [comment]
const colors = Object.fromEntries(Object.keys(themeColors).map(e => {
    const colorValue = `${colorFormat}(var(${getVarName(e)}-${colorFormat}))`;
    return [e, colorValue];
  }));  如果colorFormat=“”  就会出现 --var()-

**Comment by chizukicn** [comment]
带有rgb或者hsl的其实是private的，建议直接这样引用
![5bac4b3696a41f37199e9d4c0c979cf9](https://github.com/unpreset/unocss-preset-palette/assets/16945858/e02cb756-0424-4602-8edb-4951399fc743)

![5ded766a9ac648f66262b8f22ee15ad4](https://github.com/unpreset/unocss-preset-palette/assets/16945858/a3749262-4c27-4319-8350-15bae00b76b6)

**Comment by chizukicn** [comment]
这里将一个themeColor分成两个css变量是为了让unocss识别出它的颜色格式，从而可以直接使用unocss内的透明度设定，例如`bg-primary bg-op-30`
